<?php $products = $this->getCategoryFeaturedProducts() ?>

<?php if ($products->count() > 0) : ?>
	<h2 class="subtitle" style="padding:10px; border-top: solid 1px #d3d3d3; border-bottom: solid 1px #d3d3d3;">Featured Products</h2>
	<div class="featured-products-swiper-container">
		<div class="swiper-wrapper">
			<?php foreach ($products as $product) : ?>
				<?php $product->load($product->getId()) ?>
				<div class="swiper-slide">
					<div class="inner">
						<a href="<?= Mage::getBaseUrl() . $product->getUrlPath() ?>">
							<img src="<?= $product->getImageUrl() ?>">
						</a>
						<h4 class="product-name"><?= $product->getName() ?></h4>
						<span class="price">
							<?= $this->getCurrentCurrencySymbol() ?><?= $product->getPrice() ?>
						</span>
					</div>
				</div>
			<?php endforeach; ?>
		</div>
	</div>
<?php endif; ?>