<?php $products = $this->getWebsiteFeaturedProducts(
	Mage::getStoreConfig('sm_featured/display/homepage_maximum_quantity')) ?>

<?php if ($products->count() > 0) : ?>
	<h2 class="subtitle">Featured Products</h2>
	<div class="featured-products-swiper-container">
		<div class="swiper-wrapper">
			<?php foreach ($products as $product) : ?>
				<?php $product->load($product->getId()) ?>
				<div class="swiper-slide">
					<div class="inner">
						<a href="<?= Mage::getBaseUrl() . $product->getUrlPath() ?>">
							<img src="<?= $product->getImageUrl() ?>">
						</a>
						<h4 class="product-name"><?= $product->getName() ?></h4>
						<span class="price">
							<?= $this->getCurrentCurrencySymbol() ?><?= $product->getPrice() ?>
						</span>
					</div>
				</div>
			<?php endforeach; ?>
		</div>
	</div>
<?php endif; ?>

<script>
	jQuery(function() {
		var gallery = jQuery('.featured-products-swiper-container').swiper({
			slidesPerView   : 'auto',
			resizeReInit    : true,
			keyboardControl : true,
			grabCursor      : true,
			autoplay        : "<?= Mage::getStoreConfig('sm_featured/display/autoplay') ?>",
			speed           : "<?= Mage::getStoreConfig('sm_featured/display/speed') ?>"
		});
	});
</script>
