<h1>My Custom Layered Navigator</h1>

<?php $displayOptioner = Mage::getSingleton('sm_filter/source_filterDisplayTypeOptions') ?>

<?php if($this->canShowBlock()): ?>
	<div class="block block-layered-nav<?php if (!$this->getLayer()->getState()->getFilters()): ?> block-layered-nav--no-filters<?php endif; ?>">
		<div class="block-title">
			<strong><span><?php echo $this->__('Shop By') ?></span></strong>
		</div>
		<div class="block-content toggle-content">
			<?php echo $this->getStateHtml() ?>
			<?php if ($this->getLayer()->getState()->getFilters()): ?>
				<div class="actions">
					<a class="btn-clear-all" href="<?php echo $this->getClearUrl() ?>"><?php echo $this->__('Clear All') ?></a>
				</div>
			<?php endif; ?>
			<?php if($this->canShowOptions()): ?>
				<p class="block-subtitle block-subtitle--filter"><?php echo $this->__('Filter') ?></p>
				<dl id="narrow-by-list">
					<?php $_filters = $this->getFilters() ?>
					<?php foreach ($_filters as $_filter): ?>
						<?php if($_filter->getItemsCount()): ?>
							<dt>
								<?php echo $this->__($_filter->getName()) ?>
							</dt>
							<dd>
								<?php $_filter->setTemplate('SM/Filter/filter.phtml') ?>
								<?php echo $_filter->getHtml() ?>
							</dd>
						<?php endif; ?>
					<?php endforeach; ?>
				</dl>
				<script type="text/javascript">decorateDataList('narrow-by-list')</script>
			<?php endif; ?>
		</div>
	</div>
<?php endif; ?>