<?php foreach ($this->getItems() as $_item): ?>
		<?php if ($_item->getCount() > 0): ?>
			<a class="layered-nav-color" data-location="<?php echo $this->urlEscape($_item->getUrl()) ?>"
			   style="background-color: <?= $_item->getLabel() ?>">
				<?php if ($this->shouldDisplayProductCount()): ?>
					<span class="count">(<?php echo $_item->getCount() ?>)</span>
				<?php endif; ?>
			</a>
		<?php else: ?>
			<span style="background-color: <?= $_item->getLabel() ?>">
				<?php if ($this->shouldDisplayProductCount()): ?>
					<span class="count">(<?php echo $_item->getCount() ?>)</span>
				<?php endif; ?>
            </span>
		<?php endif; ?>
<?php endforeach ?>