<style>
	#header {
		border-bottom: none;
	}

	#sm-megamenu2-container {
		z-index: 999999999999999999;
	}
	#sm-megamenu2 {
		position: relative;
		background-color: #000000;
	}
	#sm-megamenu2 > li {
		float: left;
	}
	#sm-megamenu2 .sm-megamenu2-label {
		display: block;
		background-color: #000000;
		color: #ffffff;
		padding: 10px 20px;
		font-size: 1em;
		border-radius: 0;
		font-weight: bold;
	}
	#sm-megamenu2 > li:hover .sm-megamenu2-label {
		background-color: red;
		color: #000000;
	}
	#sm-megamenu2 .sm-megamenu2-panel {
		position: absolute;
		display: none;
		width: 100%;
		top: 100%;
		left: 0;
		background-color: #000000;
		padding: 15px 20px;
		z-index: 999999999999999999;
	}
	#sm-megamenu2 > li:hover .sm-megamenu2-panel {
		display: block;
	}

	.sm-megamenu2-parent, .sm-megamenu2-child {
		line-height: 2em;
	}
	.sm-megamenu2-parent > li {
		float: left;
		overflow: hidden;
		width: calc(100% / 6);
		padding-bottom: 15px;
	}
	.sm-megamenu2-parent > li > a {
		color: red;
		font-weight: bold;
	}
	.sm-megamenu2-child > li {
		padding-left: 15px;
		border-left: solid 1px red;
	}
</style>

<div id="sm-megamenu2-container">
	<ul id="sm-megamenu2" class="clearfix">
		<?php foreach ($this->getMenuItems() as $item) : ?>
			<?php $itemType = $item->getItemType() ?>
			<li>
				<?php if (SM_MegaMenu2_Model_Source_ItemType::LINK == $itemType) : ?>
					<a class="sm-megamenu2-label" href="<?= $item->getLink() ?>">
						<?= $item->getLabel() ?>
					</a>

				<?php elseif (SM_MegaMenu2_Model_Source_ItemType::BLOCK == $itemType) : ?>
					<span class="sm-megamenu2-label">
						<?= $item->getLabel() ?>
					</span>
					<div class="sm-megamenu2-panel">
						<?= $this->getLayout()->createBlock('cms/block')->setBlockId($item->getBlockId())->toHtml() ?>
					</div>

				<?php elseif (SM_MegaMenu2_Model_Source_ItemType::CATEGORY == $itemType) : ?>
					<?php $category = Mage::getModel('catalog/category')->load($item->getCategoryId()) ?>
					<?php $children = Mage::getModel('catalog/category')
						->getCollection()
						->addAttributeToSelect('name')
						->addAttributeToFilter('parent_id', $category->getId()) ?>

					<span class="sm-megamenu2-label">
						<?= $category->getName() ?>
					</span>
					<div class="sm-megamenu2-panel sm-megamenu2-category">
						<ul class="sm-megamenu2-parent">
							<?php foreach ($children as $child) : ?>
								<?php $grandChildren = Mage::getModel('catalog/category')
									->getCollection()
									->addAttributeToSelect('name')
									->addAttributeToFilter('parent_id', $child->getId()) ?>
								<li>
									<a href="<?= $child->getUrl($child) ?>"><?= $child->getName() ?></a>
									<ul class="sm-megamenu2-child">
										<?php foreach ($grandChildren as $grandChild) : ?>
											<li>
												<a href="<?= $grandChild->getUrl($grandChild) ?>"><?= $grandChild->getName() ?></a>
											</li>
										<?php endforeach; ?>
									</ul>
								</li>
							<?php endforeach; ?>
						</ul>
					</div>
				<?php endif; ?>
			</li>
		<?php endforeach; ?>
	</ul>
</div>